Add terminal-wide report command
OpenBB-finance/OpenBBTerminal pull request #1709
Opened 2022-04-18 14:24 UTC by minhhoang1023

# Description
- Add terminal-wide report command with auto-completion for the commands
- Connect with Airtable DB for storage

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

2022-04-20 16:46 UTC, jmaslek commented
Not necessary, but is int possible to use nocoDB as an air table alternative?

(https://github.com/nocodb/nocodb)

2022-04-20 17:01 UTC, DidierRLopes requested changes
This command shouldn't be "report" but "support".

We already use "reports" naming for other features and we don't want to have that confusion here.

2022-04-22 12:01 UTC, minhhoang1023 commented
> Not necessary, but is it possible to use nocoDB as an air table alternative?
> 
> (https://github.com/nocodb/nocodb)

Ooh that looks nice! airtable is not cheap, so I could look into this once the engagement grows out of scope for Google Sheets

2022-05-10 10:31 UTC, DidierRLopes requested changes
Comments below.

On top of that can you do a quick thing for me?

This is my welcome screen
<img width="1674" alt="Screenshot 2022-05-10 at 11 27 35" src="https://user-images.githubusercontent.com/25267873/167608382-b72fa449-f4f5-4dc9-b4a0-649fc57dfe24.png">

Can we change it to this and put it inside:
<img width="1703" alt="Screenshot 2022-05-10 at 11 30 19" src="https://user-images.githubusercontent.com/25267873/167608826-af340b9c-c69e-4462-814a-63e3ebe2c958.png">

Here is the text:
```
[info]Get API keys from data providers to access more features.[/info]
    For more instructions use: 'keys' 
```

On top of that when displaying terminal version, mine is showing vREPLACE_ME, which is not ideal. Can you check if the str is different than REPLACE_ME and if it's not just not display any version?

Thanks!!

2022-05-10 10:31 UTC, DidierRLopes commented on openbb_terminal/parent_classes.py
> +            "--msg",
let's allow `-m`

2022-05-10 10:31 UTC, DidierRLopes commented on openbb_terminal/parent_classes.py
> +        parser.add_argument(
and `-t`

2022-05-10 15:00 UTC, DidierRLopes commented
> @DidierRLopes @minhhoang1023 the vREPLACE_ME will be fixed by the time we do the next release. This relates to poetry not installing the openbb_terminal package correctly into the local environment. Known issue. Let's keep it out of the scope of this PR, please

Thought it would be a 2 liner change and therefore worth the protection added here - seems sloppy currently. Since I use advanced mode I only saw this now.

2022-05-10 15:02 UTC, piiq commented
> > @DidierRLopes @minhhoang1023 the vREPLACE_ME will be fixed by the time we do the next release. This relates to poetry not installing the openbb_terminal package correctly into the local environment. Known issue. Let's keep it out of the scope of this PR, please
> 
> Thought it would be a 2 liner change and therefore worth the protection added here - seems sloppy currently. Since I use advanced mode I only saw this now.

It's 2 symbols if you hardcode the version number =) . I was trying to fetch the version number from pyproject.toml on boot and it fails in some environments

2022-05-10 18:14 UTC, DidierRLopes approved these changes
Amazing 🙌🏽🙌🏽🙌🏽 legooo

2022-05-10 18:45 UTC, merged