Add crypto DD commands
OpenBB-finance/OpenBBTerminal pull request #1710
Opened 2022-04-18 15:26 UTC by minhhoang1023

# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

2022-04-26 16:09 UTC, jose-donato requested changes
<img width="809" alt="image" src="https://user-images.githubusercontent.com/43375532/165343139-4bd63d7d-0925-47b2-8ea1-4deb320375d6.png">

What does this activity count mean? number of commits? Maybe we can clarify on the chart?

<img width="964" alt="image" src="https://user-images.githubusercontent.com/43375532/165343432-579c41b2-b945-4dbd-9a10-0b9e643c4a0a.png">
Just a detail but can we prettify the column names? How to do it [here](https://github.com/OpenBB-finance/OpenBBTerminal/blob/e1fd37a5273b2307b3a8e3eb3e117a9b1375b57e/openbb_terminal/cryptocurrency/due_diligence/messari_model.py#L362)


Apart from these small details awesome work as always 🚀

2022-04-26 16:09 UTC, jose-donato commented on openbb_terminal/cryptocurrency/due_diligence/dd_controller.py
> +            choices=cryptopanic_model.CATEGORIES,
missing autocompletion

2022-04-26 16:09 UTC, jose-donato commented on openbb_terminal/cryptocurrency/due_diligence/dd_controller.py
> +            choices=cryptopanic_model.FILTERS,
missing autocompletion

2022-04-26 16:09 UTC, jose-donato commented on openbb_terminal/cryptocurrency/due_diligence/dd_controller.py
> +            choices=cryptopanic_model.REGIONS,
missing autocompletion

2022-04-26 16:09 UTC, jose-donato commented on openbb_terminal/cryptocurrency/due_diligence/dd_controller.py
> +            choices=cryptopanic_model.SORT_FILTERS,
missing autocompletion

2022-04-26 16:40 UTC, piiq requested changes
This looks very nice
Can you also add these commands to a test***.openbb file in the scripts folder?

2022-04-27 08:40 UTC, minhhoang1023 commented
@piiq @jose-donato Was looking for this detailed level of review. Thanks guys 🚀 All done!

2022-04-27 08:43 UTC, piiq approved these changes
🚀

2022-04-27 12:31 UTC, jose-donato approved these changes
🚀

2022-04-27 12:49 UTC, merged