Adds an additional ~50 global or sector indices; improves global coverage and autocomplete.
OpenBB-finance/OpenBBTerminal pull request #1746
Opened 2022-04-27 06:01 UTC by deeleeramone

The change to this file adds approximately fifty global indices to autocomplete and  the table: /economy/index -si

For country-specific indices (outside of US or 'global'), the argument is prefaced with the standard two-letter country code for the index. All volatility indices are prefaced with cboe. I.e., cboe-vix, cboe-shortvol.

Where not using USD as the denominating index base currency, the currency is listed in the name.

```
(🦋) /economy/ $ index -si
                                     Major Indices                                     
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Argument          ┃ Name                                            ┃ Ticker        ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ sp500             │ S&P 500 Index                                   │ ^GSPC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp400             │ S&P 400 Mid Cap Index                           │ ^SP400        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp600             │ S&P 600 Small Cap Index                         │ ^SP600        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp500tr           │ S&P 500 TR Index                                │ ^SP500TR      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-xsp            │ S&P 500 Mini SPX Options Index                  │ ^XSP          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nyse-ny           │ NYSE US 100 Index                               │ ^NY           │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ dow-djus          │ Dow Jones US Index                              │ ^DJUS         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nyse              │ NYSE Composite Index                            │ ^NYA          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ amex              │ NYSE-AMEX Composite Index                       │ ^XAX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nasdaq            │ Nasdaq Composite Index                          │ ^IXIC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russell1000       │ Russell 1000 Index                              │ ^RUI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russell2000       │ Russell 2000 Index                              │ ^RUT          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ cboe-bxr          │ CBOE Russell 2000 Buy-Write Index               │ ^BXR          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ cboe-bxrt         │ CBOE Russell 2000 30-Delta Buy-Write Index      │ ^BXRT         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russell3000       │ Russell 3000 Index                              │ ^RUA          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russellvalue      │ Russell 2000 Value Index                        │ ^RUJ          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russellgrowth     │ Russell 2000 Growth Index                       │ ^RUO          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ dow-dja           │ Dow Jones Composite Average Index               │ ^DJA          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ dow-dji           │ Dow Jones Industrial Average Index              │ ^DJI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ca-tsx            │ TSX Composite Index (CAD)                       │ ^GSPTSE       │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ mx-ipc            │ IPC Mexico Index (MXN)                          │ ^MXX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ arca-mxy          │ NYSE ARCA Mexico Index (USD)                    │ ^MXY          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ br-bvsp           │ IBOVESPA Sao Paulo Brazil Index (BRL)           │ ^BVSP         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ eu-fteu1          │ FTSE Eurotop 100 Index (EUR)                    │ ^FTEU1        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ eu-speup          │ S&P Europe 350 Index (EUR)                      │ ^SPEUP        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ eu-n100           │ Euronext 100 Index (EUR)                        │ ^N100         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftse100           │ FTSE Global 100 Index (GBP)                     │ ^FTSE         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftse250           │ FTSE Global 250 Index (GBP)                     │ ^FTMC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftse350           │ FTSE Global 350 Index (GBP)                     │ ^FTLC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftai              │ FTSE AIM All-Share Global Index (GBP)           │ ^FTAI         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ uk-ftas           │ UK FTSE All-Share Index (GBP)                   │ ^FTAS         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ uk-spuk           │ S&P United Kingdom Index (PDS)                  │ ^SPUK         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ uk100             │ CBOE UK 100 Index (GBP)                         │ ^BUK100P      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ie-iseq           │ ISEQ Irish All Shares Index (EUR)               │ ^ISEQ         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nl-aex            │ Euronext Dutch 25 Index (EUR)                   │ ^AEX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nl-amx            │ Euronext Dutch Mid Cap Index (EUR)              │ ^AMX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ at-atx            │ Wiener Börse Austrian 20 Index (EUR)            │ ^ATX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ch-stoxx          │ Zurich STXE 600 PR Index (EUR)                  │ ^STOXX        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ch-stoxx50e       │ Zurich ESTX 50 PR Index (EUR)                   │ ^STOXX50E     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ch-ssip           │ Swiss All Shares Index (CHF)                    │ SSIP.SW       │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ch-airlines       │ STXE TM Airlines Index (EUR)                    │ U0A.Z         │
├───────────────────┼──────────────────────────────────── [...]

2022-04-28 05:40 UTC, JerBouma requested changes
@deeleeramone Please fix the linting then merging is ok for me.

2022-05-02 17:46 UTC, DidierRLopes commented
@deeleeramone can u have a look at this so we can merge it?

2022-05-03 10:07 UTC, DidierRLopes approved these changes

2022-05-03 10:08 UTC, JerBouma approved these changes

2022-05-03 10:08 UTC, merged

2022-10-11 07:37 UTC, deeleeramone commented
I don’t know what I’m supposed to do here.


12
 <https://github.com/OpenBB-finance/OpenBBTerminal/runs/6261683468?check_suite_focus=true#step:9:12>Skipping .ipynb files as Jupyter dependencies are not installed.
13
 <https://github.com/OpenBB-finance/OpenBBTerminal/runs/6261683468?check_suite_focus=true#step:9:13>You can fix this by running ``pip install black[jupyter]``
14
 <https://github.com/OpenBB-finance/OpenBBTerminal/runs/6261683468?check_suite_focus=true#step:9:14>would reformat openbb_terminal/economy/yfinance_model.py
15
 <https://github.com/OpenBB-finance/OpenBBTerminal/runs/6261683468?check_suite_focus=true#step:9:15>
16
 <https://github.com/OpenBB-finance/OpenBBTerminal/runs/6261683468?check_suite_focus=true#step:9:16>Oh no! 💥 💔 💥
17
 <https://github.com/OpenBB-finance/OpenBBTerminal/runs/6261683468?check_suite_focus=true#step:9:17>1 file would be reformatted, 1197 files would be left unchanged.
18
 <https://github.com/OpenBB-finance/OpenBBTerminal/runs/6261683468?check_suite_focus=true#step:9:18>Error: Process completed with exit code 1.

> On May 2, 2022, at 10:47 AM, didierlopes.eth ***@***.***> wrote:
> 
> 
> @deeleeramone <https://github.com/deeleeramone> can u have a look at this so we can merge it?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/OpenBB-finance/OpenBBTerminal/pull/1746#issuecomment-1115169623>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AUOMPBVLTNMK2WEDGYD2OEDVIAIJLANCNFSM5UN7BXCQ>.
> You are receiving this because you were mentioned.
>