stock search error fix
OpenBB-finance/OpenBBTerminal pull request #1761
Opened 2022-05-03 20:50 UTC by PzaThief

#1758 error fix.
Just after fix that issue, I found another error about japan stock exchange "S" is not in market_coverage_suffix variable. So I added it .

2022-05-04 16:24 UTC, piiq commented on openbb_terminal/stocks/stocks_controller.py
> +def choiceCheckAfterAction(choice):
wow, a metaclass in the wild

2022-05-04 17:22 UTC, piiq requested changes
@PzaThief thank you for the PR

The integration tests pass and the command arguments that have spaces work in both terminal and .openbb scripts

As a change request I would ask you to add a docstring to `choiceCheckAfterAction` and `ActionClass`

Do you think it would be beneficial to make the `choiceCheckAfterAction` available to other controllers by moving it out of the stocks_controller? @Chavithra have a look 👀, will these ideas help resolving the slash issue?

2022-05-05 06:59 UTC, PzaThief commented
@piiq 
> The integration tests pass and the command arguments that have spaces work in both terminal and .openbb scripts

Thank you for check it.
> As a change request I would ask you to add a docstring to `choiceCheckAfterAction` and `ActionClass`

Okay. I'll change it soon.
> Do you think it would be beneficial to make the `choiceCheckAfterAction` available to other controllers by moving it out of the stocks_controller?

before your comment I couldn't think about it. but as your comment, this issue is not just for stocks_controller. So I'll move it out like AllowArgsWithWhiteSpace in openbb_terminal.helper_classes

2022-05-07 10:17 UTC, piiq approved these changes

2022-05-07 15:44 UTC, merged