Portfolio Attribution Menu
OpenBB-finance/OpenBBTerminal pull request #1773
Opened 2022-05-06 16:05 UTC by JerBouma

# Description
This menu will be featuring a whole bunch of portfolio attribution commands. This allows you to understand how your portfolio performed via a variety of metrics comparing it to a benchmark to determine any alpha obtained. This is absolutely crucial to determine if active management has been beneficial.

# How has this been tested?
Not yet.

# Checklist:
- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

2022-05-06 16:06 UTC, JerBouma commented
@jmaslek Initial set-up of the Portfolio menu but have a look if you like. Still a lot to do though.

2022-05-12 18:26 UTC, jmaslek commented
looking through images:

spelling:
```
2022 May 12, 06:23 (🦋) /portfolio/ $ alloc countries
alloLess than the limit 10 are shown because the portfolio only has 5 countries.
```

The zeros show as ` 0.00e+00   ` and my personal pet peeve of the date times showing with the times :P ` 2010-05-03 00:00:00 `

2022-05-12 18:27 UTC, jmaslek commented on openbb_terminal/portfolio/allocation_model.py
> +def obtain_assets_allocation(benchmark_info: Dict, trade_value):
type hint on trade value

2022-05-12 18:35 UTC, jmaslek commented on openbb_terminal/portfolio/portfolio_view.py
> +        )
drop

2022-05-12 18:39 UTC, jmaslek approved these changes
couple small comments on printing but the rest looks good to me for now

2022-05-12 18:40 UTC, jmaslek commented
You also goofed the main terminal menu:

```
│ >   econometrics                                                                                                                                                          │
│                                                                                                                                                                           │
│ >   portfolio      
```

2022-05-12 18:43 UTC, jmaslek requested changes
```
2022 May 12, 14:43 (🦋) /portfolio/ $ load Public_Equity_Orderbook.xlsx

Portfolio: Public_Equity_Orderbook.xlsx
Risk Free Rate: 0

2022 May 12, 14:43 (🦋) /portfolio/ $ rolling
Error: 'Portfolio' object has no attribute 'benchmark_returns'
```

2022-05-13 07:15 UTC, JerBouma commented on openbb_terminal/portfolio/portfolio_view.py
> +        )
As in remove from the code, if so why?

2022-05-13 07:44 UTC, JerBouma commented
> looking through images:
> 
> spelling:
> 
> ```
> 2022 May 12, 06:23 (🦋) /portfolio/ $ alloc countries
> alloLess than the limit 10 are shown because the portfolio only has 5 countries.
> ```
> 
> The zeros show as `0.00e+00 ` and my personal pet peeve of the date times showing with the times :P `2010-05-03 00:00:00`

So this is just me typing too quickly and thus the next command I am typing also showing. Will fix date format.

2022-05-13 08:50 UTC, JerBouma commented
Should all be fixed now and made some tables look a bit nicer.

2022-05-14 11:41 UTC, DidierRLopes approved these changes

2022-05-14 11:42 UTC, merged