patternize validation of axes count with typo fix
OpenBB-finance/OpenBBTerminal pull request #1781
Opened 2022-05-07 19:39 UTC by PzaThief

in view functions axis validation and store variable codes  have many errors of below situations and have problem about hard to read.
1. mismatch between validation code and unpacking to store variable
2. mismatch between validation code and console print message
3. mismatch between validation code and unpacking to store variable
4. mismatch between validation code and parameter docs
etc.

So I made pattern about validation of axes count and fix typos.
I tried to check error of my commit as far as possible, but there can be errors. So please let me know if anyone finds errors.

2022-05-07 23:57 UTC, DidierRLopes commented
I like what you did there! @PzaThief 🚀

2022-05-11 19:43 UTC, piiq requested changes
Nice one 🙌
I've left a request for type-hints and a docstring

2022-05-12 09:47 UTC, PzaThief commented on openbb_terminal/helper_funcs.py
> +):
> Can you add type-hints and a docstring please?

Oh. I missed it. Thank you for check it. :D

2022-05-17 13:22 UTC, Chavithra commented
Fix conflict + CI errors
@piiq I let you check again before merging

2022-05-17 16:43 UTC, piiq approved these changes

2022-05-17 18:20 UTC, merged

2022-05-17 18:21 UTC, piiq commented
thanks @PzaThief