Simplify way to generate report templates
OpenBB-finance/OpenBBTerminal pull request #1788
Opened 2022-05-09 02:03 UTC by DidierRLopes

Self-descriptive.

@jose-donato you may want to wait for this PR before you add one for crypto.

2022-05-09 13:01 UTC, piiq requested changes
Could you please add/expand docstrings and add type hints in the widgets functions

2022-05-09 13:44 UTC, DidierRLopes commented on openbb_terminal/jupyter/widget_helpers.py
> +def kpi(thresholds, sentences, value):
Yup, since the ones above weren't complete I wanted to make sure you were happy with my code before writing the documentation. Will add it now

2022-05-09 13:46 UTC, piiq commented on openbb_terminal/jupyter/widget_helpers.py
> +def kpi(thresholds, sentences, value):
you made me look twice if there's some catch 😂

2022-05-10 06:22 UTC, piiq approved these changes

2022-05-10 06:22 UTC, merged