Changing menu dialogue for keys menu to be more apparent on how to add an api key
OpenBB-finance/OpenBBTerminal pull request #1971
Opened 2022-06-20 23:29 UTC by simmonsj330

# Description
Changed menu so that users know what command to use to add a new api key. Specifically told users to see the help dialogue for each key because some keys need optional arguments such as the reddit api which needs client id, client secret, etc.

<img width="909" alt="Screen Shot 2022-06-20 at 6 26 13 PM" src="https://user-images.githubusercontent.com/53658028/174688633-f34fef22-415e-45f5-9ed4-d36c08f36362.png">

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.

2022-06-21 21:18 UTC, minhhoang1023 commented
Good call. As there can be multiple variables to be set, depending on the API.

Can you do me a favor and remove the "through environment variables"? People who use the installer would not know what is environment variable.

2022-06-21 21:18 UTC, minhhoang1023 approved these changes

2022-06-24 22:51 UTC, DidierRLopes commented
@minhhoang1023 if you still want changes on a PR, let's not accept it straight.

I was about to merge this because tests passed and a change was approved. I usually go back and check comments to see what happens but other person from the team may not.

2022-06-24 22:52 UTC, DidierRLopes requested changes
Change wording to remove "through environment variables" following @minhhoang1023 suggestion

2022-06-28 19:41 UTC, DidierRLopes approved these changes

2022-06-28 19:41 UTC, merged