Fixes #2053
OpenBB-finance/OpenBBTerminal pull request #2063
Opened 2022-07-09 18:00 UTC by colin99d

# Description

There is no need to reset the attributes of the class. The dictionary remembers them.

# How has this been tested?

Reran `r` and did not get an error.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

2022-07-11 18:53 UTC, DidierRLopes requested changes
This doesn't fix the issue, but masks it.

In this case we can't get the data from the submenu to the `po` menu. This is not the goal here.

2022-07-11 19:10 UTC, colin99d commented
Because I think we just need to change the way we do call_reset. Although I might be wrong.

2022-07-12 08:31 UTC, DidierRLopes commented
> Every or just when you reload?

So the idea is that if you change stuff on the submenu (params) that affects the menu above (po). By removing those lines of code you are not getting anything that was updated on the submenu.

You avoid the warning but lose the capability of getting that data.

BTW, it's not only on "reset" the issue. Also on "exit"

2022-07-14 11:19 UTC, colin99d commented
@jmaslek feel free to use your "dirty" fix here. I never intended for this to be a functionality we had, so it would take me some thinking to come up with an answer.

2022-07-14 11:45 UTC, DidierRLopes commented
> @jmaslek feel free to use your "dirty" fix here. I never intended for this to be a functionality we had, so it would take me some thinking to come up with an answer.

@colin99d I was pretty certain that this functionality was to access variables within a controller. Hence why you created a dictionary of the controllers, to access them. 

Otherwise, what was the use case? I can't recall

2022-07-14 11:47 UTC, colin99d commented
> > @jmaslek feel free to use your "dirty" fix here. I never intended for this to be a functionality we had, so it would take me some thinking to come up with an answer.
> 
> @colin99d I was pretty certain that this functionality was to access variables within a controller. Hence why you created a dictionary of the controllers, to access them.
> 
> Otherwise, what was the use case? I can't recall

I created it so that if you left a menu and then came back, it would still be saved.

2022-07-14 11:50 UTC, DidierRLopes commented
> > > @jmaslek feel free to use your "dirty" fix here. I never intended for this to be a functionality we had, so it would take me some thinking to come up with an answer.
> > 
> > 
> > @colin99d I was pretty certain that this functionality was to access variables within a controller. Hence why you created a dictionary of the controllers, to access them.
> > Otherwise, what was the use case? I can't recall
> 
> I created it so that if you left a menu and then came back, it would still be saved.

Yup. So that means that that controller in that dictionary should have access to those variables because they were "saved" in advance.

This sounds like it's the use case you added. The main thing to understand is why you can't access those variable from the dictionary directly? Do we need to somehow load it first or something? Because if you quit the menu, and then do it again, I believe it works

2022-07-14 11:55 UTC, colin99d commented
> Yup. So that means that that controller in that dictionary should have access to those variables because they were "saved" in advance.
> 
> This sounds like it's the use case you added. The main thing to understand is why you can't access those variable from the dictionary directly? Do we need to somehow load it first or something? Because if you quit the menu, and then do it again, I believe it works

I imagine we need to do modify the reset function somehow. Also I am confused about exit, doesnt exit leave the entire terminal?

2022-07-14 12:01 UTC, DidierRLopes commented
> > Yup. So that means that that controller in that dictionary should have access to those variables because they were "saved" in advance.
> > This sounds like it's the use case you added. The main thing to understand is why you can't access those variable from the dictionary directly? Do we need to somehow load it first or something? Because if you quit the menu, and then do it again, I believe it works
> 
> I imagine we need to do modify the reset function somehow. Also I am confused about exit, doesnt exit leave the entire terminal?

Yes. The issue is the same in both reset/exit. The issue is in the fact that the controller doesn't exist on the dictionary when we leave the params menu. Hence why I asked you to have a look at it since it should have been "saved".

2022-07-15 10:16 UTC, DidierRLopes commented
Check #2090

2022-07-15 10:16 UTC, closed without merging