Ccxt
OpenBB-finance/OpenBBTerminal pull request #2158
Opened 2022-07-24 16:03 UTC by jose-donato

# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

2022-07-24 18:16 UTC, DidierRLopes commented
Don't forget to update the website content as well 😄

2022-07-24 18:20 UTC, jose-donato commented
> Don't forget to update the website content as well 😄

Yup it's still a WIP

2022-07-26 00:08 UTC, DidierRLopes commented
Can we allow to not add a "-e":

<img width="386" alt="Screenshot 2022-07-26 at 01 08 05" src="https://user-images.githubusercontent.com/25267873/180895349-91e56569-bed4-4b27-9f54-d11a331e385b.png">

2022-07-26 00:13 UTC, DidierRLopes requested changes
Couple of requests

2022-07-26 00:13 UTC, DidierRLopes commented on openbb_terminal/cryptocurrency/due_diligence/ccxt_model.py
> +def get_orderbook(exchange_id: str, coin: str, vs: str):
Can we add return type with the `-> Dict`

2022-07-26 00:13 UTC, DidierRLopes commented on openbb_terminal/cryptocurrency/due_diligence/ccxt_view.py
> +        Export dataframe data to csv,json,xlsx file"""
The `"""` should be 1 line below

2022-07-26 00:13 UTC, DidierRLopes commented on openbb_terminal/cryptocurrency/due_diligence/ccxt_view.py
> +        Export dataframe data to csv,json,xlsx file"""
`"""` one line below

2022-07-26 00:13 UTC, DidierRLopes commented on openbb_terminal/cryptocurrency/due_diligence/dd_controller.py
> +            choices["ob"]["-e"] = {c: None for c in self.ccxt_exchanges}
Can we add: 
```
choices["ob"] = {c: None for c in self.ccxt_exchanges}
choices["ob"]["-e"] = {c: None for c in self.ccxt_exchanges}
choices["trades"] = {c: None for c in self.ccxt_exchanges}
choices["trades"]["-e"] = {c: None for c in self.ccxt_exchanges}
```

2022-07-26 00:31 UTC, DidierRLopes approved these changes

2022-07-26 09:04 UTC, merged