Add a command as well as links to the survey
OpenBB-finance/OpenBBTerminal pull request #2174
Opened 2022-07-25 13:42 UTC by JerBouma

This PR does the following:
- Add a command `survey` that opens the most recent survey.
- Add a link within the documentation to fill in the most recent survey.
- Add a link in the exit message about filling in the survey.

The link, https://openbb.co/survey, still needs to be defined.

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/46355364/180791447-0225a3b3-fc38-4bba-aedd-8c5011ad2dd8.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/180791316-8ac3c185-e789-4156-8936-721d46805ad8.png">

<img width="910" alt="image" src="https://user-images.githubusercontent.com/46355364/180791498-f83c5017-e6d7-4bcb-a627-03f87b83e3c8.png">

2022-07-25 15:17 UTC, minhhoang1023 commented
Thanks for setting this up Jer! 🙌 

@piiq @andrewkenreich A quick question about the installer! My idea is that we can add the Survey link in the exit message for the Terminal. @JerBouma mentioned that it will only appear when people type `q` to exit. Is there any way we can still display the message when people exit in a different way?

2022-07-25 17:10 UTC, piiq commented
> Is there any way we can still display the message when people exit in a different way?

If the user closes the window the window just closes and there is no exit per se. We can display survey link in the start message, or in some other place

2022-07-26 08:53 UTC, minhhoang1023 commented
It throws an error when I launched the command.

![image](https://user-images.githubusercontent.com/40023817/180965939-256d5acf-75ca-48bb-aca2-b55f25f4709e.png)

2022-07-26 08:54 UTC, minhhoang1023 requested changes

2022-07-26 08:54 UTC, minhhoang1023 commented on terminal.py
> +    def call_survey(self) -> None:
since we are not using any class attribute, it can be a static class here.

2022-07-26 08:56 UTC, JerBouma commented
Fixed the survey command not working.  Does it matter much it isn't a static method?

2022-07-26 09:02 UTC, minhhoang1023 commented
@JerBouma it's software engineering best practice. So that an instance doesn't have to be instantiated each time you call it.

It would take less than 1 min to fix it, and we can keep the code base to a high-quality standard.

2022-07-26 09:02 UTC, minhhoang1023 commented
Awesome! Working now 🚀

2022-07-26 09:08 UTC, JerBouma commented
> 

Could you suggest how?

2022-07-26 09:10 UTC, minhhoang1023 commented
For the survey, we could add "Take 2 mins to fill in our survey" or "Fill in our 2-minute survey". Letting people know that this is extremely QUICK to do!

Looks great overall

2022-07-26 09:14 UTC, JerBouma commented
![image](https://user-images.githubusercontent.com/46355364/180970353-d50c636d-9abc-4f82-b68c-27a2505d3848.png)

![image](https://user-images.githubusercontent.com/46355364/180970557-58157868-401d-465e-887d-fd6f1e9069d1.png)

Better?

2022-07-26 09:15 UTC, minhhoang1023 commented
> > @JerBouma it's software engineering best practice. So that an instance doesn't have to be instantiated each time you call >it.
> > It would take less than 1 min to fix it, and we can keep the code base to a high-quality standard.
> 
> Could you suggest how?

Just need to add the @staticmethod and remove the self. Like this

```
    @staticmethod
    def call_survey(_) -> None:
        """Process survey command"""
        webbrowser.open("https://openbb.co/survey")
```

2022-07-26 09:18 UTC, JerBouma commented
Done done

2022-07-26 09:23 UTC, minhhoang1023 approved these changes
LGG

2022-07-26 09:54 UTC, piiq approved these changes

2022-07-26 10:00 UTC, merged