Improved sorting capabilities in the news function
OpenBB-finance/OpenBBTerminal pull request #2682
Opened 2022-09-30 06:36 UTC by colin99d

# Description

Fixes #2681 

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the api still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

2022-09-30 21:59 UTC, montezdesousa requested changes
Hey @colin99d, what do you think of moving the `sort_values` inside the model instead? This way both model and view have the same output and api users have the sorted news dataframe with `openbb.common.news(term="UK Pension fund")`

Also can you can remove this line from `api.py` virtual paths? -> `"view": "openbb_terminal.common.feedparser_view.display_news"` 

Does not make sense to expose the view in the api in this case it just prints the news.

2022-10-02 11:35 UTC, colin99d commented
@montezdesousa. Updates made!

2022-10-03 09:41 UTC, montezdesousa approved these changes

2022-10-03 09:42 UTC, montezdesousa commented
> @montezdesousa. Updates made!

tks!

2022-10-03 09:44 UTC, merged