refactor: divide load() for each currency data source
OpenBB-finance/OpenBBTerminal pull request #3114
Opened 2022-10-27 04:37 UTC by gsegatti

Hello, folks! This is my first PR around here, so I tried to do something simple. Ended up being bigger than I thought.
Please have a go at it and let me know if you have any suggestions.

# Description
- Just a small refactor of `load()` in `/cryptocyrrency/cryptocurrency_helpers.py`
    - Created a function for each of the sources we can retrieve data from, downsizing `load()` itself.

2022-10-27 04:38 UTC, gsegatti commented
I'm afraid the `Check validity of reserved arguments` lint isn't passing but it is quite late and I'll check it tomorrow.

2022-10-27 14:46 UTC, gsegatti commented
Seems like all the CI tests passed, only missing a tag apparently.

2022-10-27 14:49 UTC, jmaslek commented
@jose-donato can you take a look :)

2022-10-27 22:34 UTC, DidierRLopes commented
Amazing @gsegatti !!

2022-10-28 14:55 UTC, jose-donato commented on openbb_terminal/cryptocurrency/cryptocurrency_helpers.py
> +    """Load crypto currency data from CCXT.
we normally do here like this:

`Load crypto currency data [Source: https://github.com/ccxt/ccxt]`

2022-10-28 14:57 UTC, jose-donato requested changes
Welcome aboard 🚀 

Everything looks good code-wise apart from the minor changes I commented. Can test it locally later today

Thanks for your contribution, if you want to contribute on more stuff related to crypto let me know

2022-10-28 14:57 UTC, jose-donato commented on openbb_terminal/cryptocurrency/cryptocurrency_helpers.py
> +    """Load crypto currency data from Coin Gecko.
Same here 
`Load crypto currency data [Source: https://www.coingecko.com/]`

2022-10-28 14:57 UTC, jose-donato commented on openbb_terminal/cryptocurrency/cryptocurrency_helpers.py
> +    """Load crypto currency data from Yahoo Finance.
`Load crypto currency data [Source: https://finance.yahoo.com/]`

2022-10-29 03:51 UTC, gsegatti commented
Thanks, @jose-donato, I will! 
I'll also keep in mind the way of formatting Source related comments. I've Fixed what you mentioned so far.

2022-11-01 11:32 UTC, jose-donato approved these changes
all good! way more clean, nice job 🚀

2022-11-01 12:05 UTC, merged