remove funds overview
OpenBB-finance/OpenBBTerminal pull request #3209
Opened 2022-10-31 12:01 UTC by taiyeoguns

# Description

- [x] Summary of the change / bug fix. - Remove `funds/overview`
- [x] Link # issue, if applicable. - Issue #2985
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

2022-10-31 13:47 UTC, jmaslek requested changes
Thanks @taiyeoguns.  In order to make sure it doesn't appear on the menu, we need to remove it from the mutual_fund_controller.py file (`mt.add_cmd("overview")`).  And then remove it from the choices list - so that it doesn't show up in autocomplete.

2022-10-31 15:52 UTC, taiyeoguns commented
Thanks @jmaslek, I've made the changes.

2022-10-31 15:57 UTC, jmaslek commented
Thanks!  I think you may run into an issue with the controller tests -- but running 

```
pytest tests/openbb_terminal/mutual_funds/test_mutual_fund_controller.py --rewrite-expected
```
should rewrite the file!

2022-11-02 13:11 UTC, jmaslek approved these changes

2022-11-02 15:30 UTC, merged