Adds Intro Guide for the Stock Options SDK Module
OpenBB-finance/OpenBBTerminal pull request #3298
Opened 2022-11-04 05:47 UTC by deeleeramone

2022-11-04 08:01 UTC, JerBouma requested changes
@deeleeramone Please put your attention to the higher level menus first, e.g. Economy, Forex, Econometrics, Portfolio. We can think of these sub-menus at a later stage.

In any case, have some suggestions and then we can still merge this one.

2022-11-04 08:01 UTC, JerBouma commented on website/content/SDK/stocks/options/_index.md
> +The data can then be cleaned for better presentation, indexing, or analysis; for example:
Let's get rid of the section down below, we show SDK functionality and not how data can be cleaned. If this step was mandatory, then it should have been in the SDK in the first place.

2022-11-06 00:57 UTC, deeleeramone commented
I would consider the Options menu as a high-level menu.

2022-11-07 08:31 UTC, JerBouma requested changes
Minor minor detail

2022-11-07 18:24 UTC, JerBouma approved these changes

2022-11-08 16:04 UTC, merged