Many improvements to the documentation
OpenBB-finance/OpenBBTerminal pull request #3562
Opened 2022-11-24 19:07 UTC by JerBouma

These things:

- Extended FAQ for Terminal and SDK
- Added Troubleshooting page to Terminal FAQ
- Integrated #3539
- Made SDK basics more coherent with Terminal
- Many grammar changes and smaller things

2022-11-24 19:53 UTC, jose-donato approved these changes
Lgtm

2022-11-24 20:56 UTC, JerBouma commented
Do not merge just yet, need to check some grammar first tomorrow.

2022-11-25 14:40 UTC, jose-donato requested changes

2022-11-25 14:40 UTC, jose-donato commented on website/content/sdk/guides/intros/portfolio/po.md
> +The Portfolio Optimization menu allows the user to apply advanced optimization techniques to a portfolio of any type and of any size. It does so by introducing a multitude of optimization techniques
always add `rel="noreferrer noopener"` when doing `target="_blank"`

2022-11-25 14:40 UTC, jose-donato commented on website/content/sdk/guides/intros/portfolio/po.md
> +The capabilities of the [Portfolio Optiminzation menu](/terminal/guides/portfolio/po) from the OpenBB Terminal are wrapped into a powerful SDK, enabling users to work with the data in a flexible envi
same as above

2022-11-25 14:40 UTC, jose-donato commented on website/content/sdk/guides/intros/portfolio/po.md
>  <a target="_blank" href="https://user-images.githubusercontent.com/46355364/171144692-dd812efd-1e95-4a71-a93f-7ae8a480fe5d.png"><img alt="OpenBB Parameters Template" src="https://user-images.githubus
same as above

2022-11-25 14:40 UTC, jose-donato commented on website/content/sdk/guides/intros/portfolio/po.md
same as above

2022-11-25 14:40 UTC, jose-donato commented on website/content/sdk/guides/intros/portfolio/po.md
> +To demonstrate the capabilities of the Portfolio Optimization menu, the entire <a href="https://www.investopedia.com/terms/s/sp500.asp" target="_blank">S&P 500 index</a> (as of 30th of May 2022) is u
same as above

2022-11-25 14:40 UTC, jose-donato commented on website/content/sdk/guides/intros/portfolio/po.md
> +It is possible to delve further into these findings with the `plot` functionality for example done by looking at the portfolio's returns <a href="https://www.investopedia.com/terms/h/histogram.asp" t
same as above

2022-11-25 14:41 UTC, jose-donato approved these changes

2022-11-25 18:10 UTC, merged