updated TA SDK guide import block with comment (more copy/paste friendly)
OpenBB-finance/OpenBBTerminal pull request #3595
Opened 2022-11-26 07:52 UTC by deeleeramone

2022-11-26 10:12 UTC, JerBouma requested changes

2022-11-26 10:12 UTC, JerBouma commented on website/content/sdk/guides/intros/stocks/comparison-analysis.md
> +## **How to Use**
Please remove the bolding, this is not required as it bolds by default.

2022-11-26 10:12 UTC, JerBouma commented on website/content/sdk/guides/intros/stocks/comparison-analysis.md
> +## **Examples**
Same comment.

2022-11-27 19:20 UTC, andrewkenreich approved these changes
all good

2022-11-27 20:01 UTC, merged