Fixed dates on yield curve functions, test functions and doc strings
OpenBB-finance/OpenBBTerminal pull request #3617
Opened 2022-11-28 03:51 UTC by pmpmchaves

# Description

Hello, this is my first pull request on the platform :) Hope it helps, let me know if you have any questions!

Fixes Bug issue: https://github.com/OpenBB-finance/OpenBBTerminal/issues/3615

- [X] Summary of the change / bug fix: 
In the SDK, when calling the function openbb.economy.ycrv(), the argument date only accepts a datetime date.
For example, it only works when converting the input into a datetime element:
get_yield_curve(datetime(2022,11,1))
How it should work:
get_yield_curve("2022-11-01")
- [x] Link # issue, if applicable: https://github.com/OpenBB-finance/OpenBBTerminal/issues/3615
- [x] Screenshot of the feature or the bug before/after fix, if applicable:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/106980009/204187953-00820f55-a7ef-4fe6-a23f-db4e950085ff.png">

- [x] Relevant motivation and context:
- [x] List any dependencies that are required for this change:

# How has this been tested?
On the OpenBB terminal:
`economy/ycrv`
`economy/ycrv -d 2022-05-23`

On the SDK (Jupyter Notebook):
`from openbb_terminal.sdk import openbb`
`openbb.economy.ycrv('2022-05-23')`
`openbb.economy.ycrv_chart('2022-05-23')`

- [x] Make sure affected commands still run in terminal:
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

2022-11-28 11:07 UTC, hjoaquim commented
Thanks for this contribution and welcome :rocket: !! Nice catch here :sunglasses:

2022-11-28 11:12 UTC, hjoaquim requested changes

2022-11-28 11:12 UTC, hjoaquim commented on openbb_terminal/economy/economy_controller.py
> -            type=valid_date,
I would keep this in order to ensure it's still a valid date, and then have `ns_parser.date.strftime("%Y-%m-%d")` passing the argument to `fred_view.display_yield_curve`. WDYT?

2022-11-28 15:35 UTC, hjoaquim approved these changes

2022-11-28 15:39 UTC, hjoaquim commented
@pmpmchaves I'm sorry to step ahead, we're trying to get rid of many bugs as possible before the release!

2022-11-28 17:15 UTC, merged

2022-11-29 09:58 UTC, pmpmchaves commented
> @pmpmchaves I'm sorry to step ahead, we're trying to get rid of as many bugs as possible before the release!

Not a problem @hjoaquim ! Happy to help :)

> Thanks for this contribution and welcome @pmpmchaves 🚀 !! Nice catch here 😎

You are very welcome, keep up the great work guys 🚀