Add tweet news in terminal toolbar
OpenBB-finance/OpenBBTerminal pull request #3757
Opened 2022-12-11 14:39 UTC by DidierRLopes

Work in progress...

<img width="1668" alt="Screenshot 2022-12-08 at 22 40 39" src="https://user-images.githubusercontent.com/25267873/206910109-7132d0dc-7dad-44de-b0ab-c948089cbb6d.png">

2022-12-13 00:28 UTC, jmaslek commented
Same thing is happening to me that was happening on the mstarpy branch.

```
Package operations: 2 installs, 80 updates, 2 removals

  • Removing setuptools (65.4.1)
  • Removing wheel (0.38.4)
```

@Chavithra @piiq Do we need to add setuptools to poetry?

2022-12-13 11:17 UTC, piiq requested changes
Please:
1. Make sure that there is exception handling in place for situations when data is queried for non-popular instruments
2. Make sure that timeouts for people who don't have twitter keys or are in networks where twitter is blocked are 1 second and less
3. Add unit tests for every function that you have added

2022-12-13 11:31 UTC, piiq commented
@jmaslek we have setuptools in poetry build system. We need an older version to support building dependencies that rely on numpy
<img width="502" alt="image" src="https://user-images.githubusercontent.com/11668535/207306838-0ed82751-b8f2-41e3-b966-5d64ef2f4d09.png">

2022-12-13 13:18 UTC, jmaslek commented
> @jmaslek we have setuptools in poetry build system. We need an older version to support building dependencies that rely on numpy <img alt="image" width="502" src="https://user-images.githubusercontent.com/11668535/207306838-0ed82751-b8f2-41e3-b966-5d64ef2f4d09.png">

So then why does poetry remove it -- but only on certain branches?

2022-12-13 14:24 UTC, DidierRLopes commented
> Please:
> 
> 1. Make sure that there is exception handling in place for situations when data is queried for non-popular instruments
> 2. Make sure that timeouts for people who don't have twitter keys or are in networks where twitter is blocked are 1 second and less
> 3. Add unit tests for every function that you have added

> 1. Make sure that there is exception handling in place for situations when data is queried for non-popular instruments

What do you mean by "when data is queried for non-popular instruments"? This displays a tweet, unrelated with any instruments?

> 2. Make sure that timeouts for people who don't have twitter keys or are in networks where twitter is blocked are 1 second and less

<img width="690" alt="Screenshot 2022-12-13 at 14 21 58" src="https://user-images.githubusercontent.com/25267873/207358391-b6d69836-9e2f-4dd0-b5db-3461c87b882c.png">

I already had a check to disable it in case the user didn't have correct API key. The timeout I left the default one as 60s, but can do 5s instead. 👍

> 3. Add unit tests for every function that you have added

Can you give me an example of what you expect the unit test for `update_news_from_tweet_to_be_displayed` to look like? Need to mockup the tweets of several users?

2022-12-13 15:29 UTC, piiq commented
Re-solved dependencies here break the dep tree and poetry can't install on a fresh env. Hold on the merge please until this is resolved

2023-02-01 23:11 UTC, jmaslek commented on openbb_terminal/helper_funcs.py
> +LAST_TWEET_NEWS_UPDATE_CHECK_TIME = datetime.now() - timedelta(hours=1)
dupe

2023-02-02 15:26 UTC, jmaslek commented on openbb_terminal/helper_funcs.py
> +    ).seconds > obbff.TOOLBAR_TWEET_NEWS_SECONDS_BETWEEN_UPDATES:
You probably want to use total_seconds here instead.  Seconds will only give you a number from 0-60 based on the timestamps.

2023-02-02 16:45 UTC, Chavithra commented on openbb_terminal/miscellaneous/scripts/economy/test_economy.openbb
> +economy
It was moved then changed.
Deleted the file.

2023-02-02 16:46 UTC, jmaslek commented
https://techcrunch.com/2023/02/01/twitter-to-end-free-access-to-its-api/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuYmluZy5jb20v&guce_referrer_sig=AQAAAIfbpM1o0f_hqTCF2yXUIeoiC3ccQaWgV2iFFqWJOffvqMdRQbVo8852Gxr578cE9oC3pd48mfMNkuFRFx2IzS0M4vF3S7HMCp1OC0bG7fnudoOMop-nyUuy2MZmAWb8NIGn6DsRGqViA6dLfEJr1Dqv0K9HeUVkH7tiekz67qCQ

2023-02-22 01:17 UTC, Chavithra approved these changes
Looks ok to me.

There is a API_TWITTER_BEARER_TOKEN loading issue : this feature requires the credentials to be loaded sooner.

But I think we should try to resolve that on the credentials refactoring that is planned.

For now it works if we put the credentials on `config_terminal.py`.

2023-02-23 12:22 UTC, merged