[WIP] Automatic i18n Translations with Huggingface 🤗 📖
OpenBB-finance/OpenBBTerminal pull request #3869
Opened 2023-01-04 14:23 UTC by martinb-bb

The goal is to get more worldwide traction with many users from all across the globe. Let's get the ball rolling on this initative.

Supports following language translation from english:
- Spanish
- French
- Italian
- Portuguese
- Mandarin
- Japanese
- Russian
- Arabic
- Hindi
- Indonesian

Next steps:
[ ] Build an automatic checker for new entries for new auto translation
[ ] Double check all translations with respective experts in languages

2023-01-05 01:28 UTC, jose-donato commented
Wow this is crazy. 

Just a note - the pt one is not pt is pt-br

2023-01-05 10:52 UTC, jose-donato commented
> > Wow this is crazy.
> > Just a note - the pt one is not pt is pt-br
> 
> @jose-donato Oh so this is Brazilian Portuguese?

The translation you have in the pr yes

2023-01-08 17:46 UTC, BychkovRY commented on openbb_terminal/miscellaneous/i18n/ru.yml
> +  _configure_: Настроить собственный терминал
_configure_: Настройте свой собственный терминал

2023-01-08 17:57 UTC, BychkovRY commented on openbb_terminal/miscellaneous/i18n/ru.yml
> +  _home_: Информация, руководства и поддержка терминала OpenBB
_home_: Информация, руководства и поддержка для OpenBB Terminal

2023-01-26 23:04 UTC, samuelstroschein commented
We'd like to chip in and provide OpenBB with a UI for contributors to add translations with [inlang/inlang](https://github.com/inlang/inlang). See as an example https://inlang.com/editor/github.com/inlang/example.

The only requirement is a [yaml plugin](https://inlang.com/documentation/plugins). We can build one.

2023-01-26 23:34 UTC, jmaslek commented
> We'd like to chip in and provide OpenBB with a UI for contributors to add translations with [inlang/inlang](https://github.com/inlang/inlang). See as an example https://inlang.com/editor/github.com/inlang/example.
> 
> The only requirement is a [yaml plugin](https://inlang.com/documentation/plugins). We can build one.

Hey!  That sounds awesome!  What steps would be needed?

2023-01-27 00:09 UTC, samuelstroschein commented
@jmaslek From your side, nothing! But wups. I just saw that your repo is 1GB large! 

We need to modify our git implementation to make inlang x OpenBB work. That's part of our [the next git](https://inlang.com/documentation/the-next-git) thesis though and therefore exactly what we want to do. 

I started a project https://github.com/orgs/inlang/projects/9. Can't give a concrete timeline yet.

2023-01-27 00:11 UTC, jmaslek commented
> @jmaslek From your side, nothing! But wups. I just saw that your repo is 1GB large!
> 
> We need to modify our git implementation to make inlang x OpenBB work. That's part of our [the next git](https://inlang.com/documentation/the-next-git) thesis though and therefore exactly what we want to do.
> 
> I started a project https://github.com/orgs/inlang/projects/9. Can't give a concrete timeline yet.

No worries!  We look forward to it!

2023-02-06 13:23 UTC, piiq requested changes
- I would remove Hindi because India has a lot more languages than just Hindi and it's either supporting more of them or sticking with a language that is still the most dominant in India (english that is)
- I would remove Arabic because it's a right-to-left written language and we have not looked into support for RTL

P.S. @soggyomelette do you speak Arabic?

2023-11-08 21:31 UTC, closed without merging