Feature/gasprices
OpenBB-finance/OpenBBTerminal pull request #3929
Opened 2023-01-11 12:31 UTC by jose-donato

# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

2023-01-19 18:05 UTC, jmaslek commented
*cough* unit tests *cough*

2023-01-19 18:06 UTC, jmaslek requested changes

2023-01-19 18:06 UTC, jmaslek commented on openbb_terminal/alternative/collectapi_model.py
> +    res = requests.get(
Can you add a timeout?  I want to start enforcing this across.

2023-01-19 18:06 UTC, jmaslek commented on openbb_terminal/config_terminal.py
> +API_COLLECTAPI_KEY = os.getenv("OPENBB_API_COLLECTAPI_KEY") or "REPLACE_ME"
needs to be added to the key menu.

2023-01-30 16:09 UTC, jose-donato commented
Apparently their free trial is only few days.. 😞

2023-01-30 20:25 UTC, jmaslek commented
jose said i could close this

2023-01-30 20:25 UTC, closed without merging