Use OpenAI API to improve bot-discord docs
OpenBB-finance/OpenBBTerminal pull request #4657
Opened 2023-04-02 05:41 UTC by DidierRLopes

# Description

- Attempts to improve bot documentation utilizing OpenAI API and using the following prompt:
```
Context: You are a developer writing a detailed documentation for a function that allows the user to retrieve {desc} utilizing the command {example} how would you explain what this command does in a single paragraph
```
where {desc} and {example} corresponds to the current description and example that each of our commands have, respectively.

The motivation was to improve our documentation, and having more quality data for training our own bot LLM.

# How has this been tested?

Just scrolled through discord documentation to make sure it looked ok. @andrewkenreich can you review and update accordingly?

Once you are happy with these, I will port them to telegram commands as well.

2023-04-03 18:38 UTC, andrewkenreich requested changes
please review my reviews

2023-04-03 18:49 UTC, DidierRLopes reviewed
missing spacing 😄

2023-04-03 18:49 UTC, DidierRLopes commented on website/content/bot/reference/discord/economy/usbonds.md
> +### Usage
missing spacing

2023-04-04 01:48 UTC, andrewkenreich approved these changes

2023-04-04 06:14 UTC, merged