Added hotfix
OpenBB-finance/OpenBBTerminal pull request #4709
Opened 2023-04-07 11:35 UTC by the-praxs

Fixed #4620 

- "--help" argument throws error when using with `eodchain` and `load` commands.
- [x] #4620 

# How has this been tested?
Tested by executing the terminal application in Python
and using the argument with the commands.

- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

2023-04-08 03:52 UTC, deeleeramone commented
Same question as #4710, @jmaslek.

2023-04-08 20:33 UTC, hjoaquim requested changes
Hello @the-praxs, thanks a lot for contributing :rocket: 

In my comments, I've suggested a slightly different implementation where we actually check for the `-h` and `--help`.

What do you think?

If we don't, we can run into this problem if the user does not supply any args: 

![image](https://user-images.githubusercontent.com/48914296/230741442-c35205dd-0144-42ca-a1a7-e91a5c60dffc.png)

2023-04-08 20:33 UTC, hjoaquim commented on openbb_terminal/stocks/options/options_controller.py
> +            # required="-h" not in other_args,
```suggestion
            required="-h" not in other_args and "--help" not in other_args,
```

2023-04-08 20:33 UTC, hjoaquim commented on openbb_terminal/stocks/options/options_controller.py
> +            # required="-h" not in other_args,
```suggestion
            required="-h" not in other_args and "--help" not in other_args,
```

2023-04-08 20:34 UTC, hjoaquim commented
The above comment, also applies to #4710

2023-04-09 11:13 UTC, the-praxs commented
@hjoaquim I also refactored some parts of the code, by using named expression to simplify assignment and conditional.

2023-04-10 08:26 UTC, hjoaquim approved these changes
Very nice additions, we don't actually have a lot of using walrus operators on the code base, so this is something we might want to look in the future :eyes: 

Well done @the-praxs

2023-04-10 08:52 UTC, merged