Test for provider field duplication check
OpenBB-finance/OpenBBTerminal pull request #5433
Opened 2023-09-12 11:16 UTC by hjoaquim

Add a test that checks for provider field duplication - those that either should be standard or optional standard.

2023-09-12 11:50 UTC, hjoaquim commented
Do not merge yet, tests should be failing on the GH actions.

2023-09-13 13:25 UTC, the-praxs requested changes
@hjoaquim you are a testing god!

2023-09-13 13:25 UTC, the-praxs commented on openbb_sdk/providers/tests/test_provider_field_dupes.py
> +            splited_path = file.split("/")
Please modify this to also work with Windows ('\')

2023-09-13 13:25 UTC, the-praxs commented on openbb_sdk/providers/tests/test_provider_field_dupes.py
> +                dupes = [x for x in fields if x in seen or seen.add(x)]
Please create a set out of this to resolve duplicate fields in the output.

2023-09-13 13:25 UTC, the-praxs commented on openbb_sdk/providers/tests/test_provider_field_dupes.py
> +                    f"Standard model: {std_cls}, Provider models: {', '.join(provider_models)}\n"
We could show the providers and the fields collectively that are found rather than just the fields!

2023-09-14 11:31 UTC, hjoaquim commented
@jmaslek it looks like only tests inside `openbb_sdk/sdk` are being collected, which causes tests on `openbb_sdk/provider` to not run. Do we need to adjust something on the actions?

2023-09-14 12:54 UTC, jmaslek commented
> @jmaslek it looks like only tests inside `openbb_sdk/sdk` are being collected, which causes tests on `openbb_sdk/provider` to not run. Do we need to adjust something on the actions?

We can actually just change the noxfile. I can push an edit shortly

2023-09-14 13:52 UTC, the-praxs commented
@henriqueio tests are failing on the CI because of `import providers` -
```python
ModuleNotFoundError: No module named 'providers'
```
Runs fine locally but not sure about CI.

2023-09-14 13:59 UTC, hjoaquim commented
You da best, thank you, @jmaslek

2023-09-17 14:18 UTC, the-praxs approved these changes
lgtm. Merge it!!

2023-09-17 17:45 UTC, merged