fix: Modify 'load' behavior to append data to existing sheet
OpenBB-finance/OpenBBTerminal pull request #5503
Opened 2023-10-01 20:17 UTC by ssahaxd

Details:
- Added logic to detect existing sheet and append data if present.
- There is no direct way to append on the sheet, so I am reading the sheet to get the last row number and then writing after that row number.

Resolves: #5472

# Description

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [x] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

2023-10-02 16:04 UTC, deeleeramone requested changes
Thanks for the quick action, and it seems like a good solution.  If you can patch in the ability to create a new sheet when the `sheet-name` is not found, I can give it a thorough check to find edge cases.

2023-10-02 19:54 UTC, ssahaxd commented on openbb_terminal/helper_funcs.py
> -                        if_sheet_exists="new",
I have fixed the 'worksheet not found' error. Moreover, I would also like to ask the user, if they provide an existing sheet name, if they want to append or replace it. I was wondering if there is some code that I can reuse to prompt the user and get the input.

2023-10-03 02:29 UTC, deeleeramone commented on openbb_terminal/helper_funcs.py
> -                        if_sheet_exists="new",
There is a Feature Flag - environment variable - that is called "overwrite".  When this is false, the user is prompted Y/N to overwrite an existing file when the exported filename already exists.  I don't see why that can't be recycled for this purpose as well.

2023-10-05 05:12 UTC, ssahaxd commented on openbb_terminal/helper_funcs.py
> -                        if_sheet_exists="new",
Changes done.
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/11327529/c5a619b4-ae20-469b-85ac-540fbc94ec9d)

2023-10-14 01:44 UTC, deeleeramone approved these changes
Nice solution, thanks for the contribution!

2023-10-14 01:49 UTC, merged