Passing tests
OpenBB-finance/OpenBBTerminal pull request #5560
Opened 2023-10-13 11:34 UTC by IgorWounds

Fix crypto, forex, economy.

2023-10-13 17:31 UTC, deeleeramone approved these changes

2023-10-13 17:32 UTC, hjoaquim requested changes
I'm getting this for economy (all of them fail with http 500):

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/48914296/c57df8f6-c164-40c3-84ee-9d9df0b5c2f8)

The other tests are good.

2023-10-13 17:32 UTC, hjoaquim commented on openbb_platform/extensions/economy/integration/test_economy_api.py
> +@pytest.mark.skip(reason="Not being picked up by the API.")
Should we open a bug with this?

2023-10-13 17:32 UTC, hjoaquim commented on openbb_platform/extensions/economy/integration/test_economy_api.py
> +                "countries": "spain",
can we also have a test for multiple countries?

2023-10-13 17:37 UTC, IgorWounds commented on openbb_platform/extensions/economy/integration/test_economy_api.py
> +@pytest.mark.skip(reason="Not being picked up by the API.")
Probably, yes.

2023-10-13 17:39 UTC, hjoaquim commented on openbb_platform/extensions/economy/integration/test_economy_api.py
> +@pytest.mark.skip(reason="Not being picked up by the API.")
Done.

2023-10-13 17:48 UTC, IgorWounds commented
> I'm getting this for economy (all of them fail with http 500):
> 
> ![image](https://user-images.githubusercontent.com/48914296/274987469-c57df8f6-c164-40c3-84ee-9d9df0b5c2f8.png)
> 
> The other tests are good.

Can you try again and check your credentials? @hjoaquim 

![Screenshot 2023-10-13 at 19 47 16](https://github.com/OpenBB-finance/OpenBBTerminal/assets/74266147/82f3c4b5-bf85-440e-91ff-67aac4a03baa)

2023-10-16 10:55 UTC, hjoaquim approved these changes
I'm getting this for economy:

2023-10-16 10:57 UTC, merged