bug #5649
OpenBB-finance/OpenBBTerminal pull request #5722
Opened 2023-11-13 22:23 UTC by ramazanguvenc

issue #5649 

convert Amount column to numeric

before:
![before](https://github.com/OpenBB-finance/OpenBBTerminal/assets/32714915/6b44bd97-541f-4b86-bcd0-792eecb64ad8)

after:
![after](https://github.com/OpenBB-finance/OpenBBTerminal/assets/32714915/c2d3fce7-635f-49ff-bc12-9e4bf5a19b1d)

2023-11-13 22:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenBB-finance/OpenBBTerminal?pullRequest=5722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenBB-finance/OpenBBTerminal?pullRequest=5722) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenBB-finance/OpenBBTerminal?pullRequest=5722) it.</sub>

2023-11-13 23:55 UTC, deeleeramone requested changes
Hi,

Thanks for the PR!

When I use the `--analysis` flags I get this error:


```
qtrcontracts --analysis downmom

Error: unsupported operand type(s) for /: 'str' and 'int'
```

2023-11-14 00:55 UTC, ramazanguvenc commented
This error existed before&after the changes I made, but cause is basically same so I took the same approach.

2023-11-16 01:00 UTC, deeleeramone approved these changes
Works as advertised, thanks!

2023-11-16 20:59 UTC, merged