Hotfix/urllib to dev group
OpenBB-finance/OpenBBTerminal pull request #5732
Opened 2023-11-14 17:30 UTC by hjoaquim

Change `pytest-recorder` to the dependencies' dev group instead, so that `urllib3` doesn't get "stuck" in a lower version.

2023-11-14 18:51 UTC, hjoaquim commented
Platform running on Colab out of the box (with `urllib3` not conflicting):

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/48914296/b6095126-7551-45c1-a1f5-88c3fb9a2df1)

2023-11-15 15:55 UTC, piiq requested changes
@hjoaquim thanks, can you look into the 2 comments i left in the diff, please?

2023-11-15 16:01 UTC, hjoaquim commented on openbb_platform/pyproject.toml
> +urllib3 = "<2.0.0"
@piiq you're correct, no need to have it here, pytest-recorder will bring a suitable version.

2023-11-15 16:17 UTC, hjoaquim commented on openbb_platform/dev_install.py
> +    extras_args = ["-E", "all", "--with", "dev"] if _extras else []
@piiq you're correct once again on this one! Thanks for the details!

2023-11-16 15:38 UTC, piiq commented on openbb_platform/platform/provider/pyproject.toml
> -urllib3 = "<2.0.0"
and here too?

2023-11-16 18:15 UTC, piiq commented on openbb_platform/platform/provider/pyproject.toml
> +urllib3 = "<3.0.0"
i mean here

2023-11-17 11:43 UTC, piiq approved these changes

2023-11-17 11:47 UTC, merged