Fix typos
OpenBB-finance/OpenBBTerminal pull request #5758
Opened 2023-11-19 07:54 UTC by omahs

Fix typos

2023-11-19 07:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenBB-finance/OpenBBTerminal?pullRequest=5758) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenBB-finance/OpenBBTerminal?pullRequest=5758) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenBB-finance/OpenBBTerminal?pullRequest=5758) it.</sub>

2023-11-20 10:34 UTC, montezdesousa approved these changes
lgtm, thanks for the contribution!

2023-11-28 09:32 UTC, hjoaquim requested changes
@omahs can you please open a new PR that follows the branch naming convention?
Could be something like `hotfix/fix-typos`. Otherwise, the CI checks won't allow it!
Thanks!

2023-11-28 15:21 UTC, omahs commented
@hjoaquim Hey, sure here's the new PR: https://github.com/OpenBB-finance/OpenBBTerminal/pull/5808

2023-11-28 15:21 UTC, closed without merging