Feature/us-treasury-prices: Adds Treasury Prices to Fixed Income
OpenBB-finance/OpenBBTerminal pull request #5776
Opened 2023-11-22 05:49 UTC by deeleeramone

This PR adds to the fixed income module, `obb.fixedincome.government.treasury_prices()`

Data comes from the US Treasury Department and contains bid/offer and EOD prices by CUSIP for on-the-run Treasuries.  There is a `date` parameter for selecting the date, the endpoint gets all CUSIPs on that date.  The `security_type` and `cusip` params are optional.

![Screenshot 2023-11-21 at 9 45 19 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/7190dead-7a0b-456e-9d31-d80e07aeb4c9)

2023-12-04 13:08 UTC, the-praxs requested changes

2023-12-04 19:08 UTC, deeleeramone commented on openbb_platform/core/openbb_core/provider/standard_models/treasury_prices.py
> +    """US Treasuries Prices Data."""
> Treasury instead of `Treasuries`

Done!

2023-12-04 19:20 UTC, deeleeramone commented on openbb_platform/providers/government_us/openbb_government_us/models/treasury_prices.py
> +        payload = f"priceDateDay={query.date.day}&priceDateMonth={query.date.month}&priceDateYear={query.date.year}&fileType=csv&csv=CSV+FORMAT"  #  type:  ignore[union-attr]  #  pylint: disable=line
Done!

2023-12-06 03:35 UTC, jmaslek approved these changes

2023-12-07 01:37 UTC, merged