Custom deprecation
OpenBB-finance/OpenBBTerminal pull request #6005
Opened 2024-01-26 18:01 UTC by hjoaquim

^

2024-01-31 18:39 UTC, the-praxs requested changes

2024-01-31 18:39 UTC, the-praxs commented on build/pypi/openbb_platform/PUBLISH.md
> +         - Run unit tests to double check the existence of deprecated endpoints
Replace "double check" with "validate" to make the language professional

2024-01-31 18:39 UTC, the-praxs commented on build/pypi/openbb_platform/PUBLISH.md
>      > Note that, in order for packages to pick up the latest versions of dependencies, it might be necessary to clear the local cache of the dependencies:
Replace "might be necessary" with "is advised" to be more precise

2024-01-31 18:39 UTC, the-praxs commented on openbb_platform/core/openbb_core/app/router.py
> +                class DeprecationSummary(str):
I think its better to move this class in the `deprecation.py` to ensure a better code structure

2024-02-01 09:25 UTC, IgorWounds approved these changes

2024-02-01 09:27 UTC, the-praxs requested changes

2024-02-01 09:27 UTC, the-praxs commented on openbb_platform/openbb/package/index.py
> +            "This endpoint is deprecated; use `/index/price/historical` instead. Deprecated in OpenBB Platform V4.1 to be removed in V4.5.",
```suggestion
            "This endpoint is deprecated since v4.1 and will be removed in v4.3; Use `/index/price/historical` instead.",
```

2024-02-01 09:27 UTC, the-praxs commented on website/content/platform/development/contributor-guidelines/deprecating_endpoints.md
> +Deprecating commands is a necessary part of maintaining the OpenBB Platform. This guide outlines the process for deprecating an endpoint.
```suggestion
Deprecating commands is essential to maintaining the OpenBB Platform. This guide outlines the process for deprecating an endpoint.
```

2024-02-01 09:27 UTC, the-praxs commented on website/content/platform/development/contributor-guidelines/deprecating_endpoints.md
> +2. Add deprecation warning
```suggestion
2. Add the deprecation warning
```

2024-02-01 09:27 UTC, the-praxs commented on website/content/platform/development/contributor-guidelines/deprecating_endpoints.md
> +1. Add new endpoint: the new endpoint that will replace the deprecated one.
```suggestion
1. Add the new endpoint that will replace the deprecated one.
```

2024-02-01 09:27 UTC, the-praxs commented on website/content/platform/development/contributor-guidelines/deprecating_endpoints.md
> +    Navigate to the **router** where the endpoint you wish to deprecate lives and add the `deprecated=True` flag and `deprecation=OpenBBDeprecationWarning(…)`, to the `@command` decorator. Refer to t
```suggestion
    Navigate to the **router** where the endpoint to be deprecated exists. Set the `deprecated` flag to `True` and add `deprecation=OpenBBDeprecationWarning(…)` argument to the decorator. Refer to the example below:
```

2024-02-01 09:27 UTC, the-praxs commented on website/content/platform/development/contributor-guidelines/deprecating_endpoints.md
> +3. Get approval from a OpenBB Platform maintainer: they will help you determine the appropriate version for the deprecation warning, and also know what to do in order to warn other OpenBB teams that
```suggestion
3. Get approval from a OpenBB Platform maintainer: We will help you determine the appropriate version for the deprecation warning, and communicate the change(s) to the relevant personnel that might depend on the endpoint you are deprecating.
```

2024-02-01 10:03 UTC, merged