[Feature] Adding interactive tables
OpenBB-finance/OpenBBTerminal pull request #6290
Opened 2024-04-05 14:27 UTC by hjoaquim

# Pull Request Template for OpenBB Developers

1. **Why**? (1-3 sentences or a bullet point list):

    - Allowing the user to have interactive tables.

2. **What**? (1-3 sentences or a bullet point list):

    - Adds a method to the charting extension that will display the interactive table (depending on `backend.isatty`)
    - Fixes the table's html.

3. **Impact** (1-2 sentences or a bullet point list):

    - Doesn't affect the current functionality of the charting extension.

4. **Testing Done**:

    - Display tables
       - `isatty=True`
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/48914296/351a22ee-dcc8-463d-a5d5-ae84ed1ebf19)

       -  `isatty=False`
          
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/48914296/389b64cc-9269-41dc-af92-d2b29cdfffe3)

2024-04-05 20:24 UTC, IgorWounds approved these changes

2024-04-05 20:39 UTC, deeleeramone requested changes
This will be great! There's a few items I've run into, a couple I'll outline here because it will blow up GitHub by commenting in table.html.

- When dates get converted to JSON, we end up with all this extra noise that makes the table much harder to read, and columns way bigger than they should be. Dates should remain dates and not get encoded with time and TZ information. Converting the column to a string instead of using the `iso` date output of `to_json` will help.

![Screenshot 2024-04-05 at 1 21 33 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/59f8cda0-d34a-4c42-91f8-49636f3b3ec3)

- Somewhere in there is a process which automatically format columns with "date-like" names, but this produces undesirable results. Perhaps kill that entirely?

![Screenshot 2024-04-05 at 1 13 46 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/65b1a69e-b623-4584-8406-2f679851c050)

In the V3 implementation there is a parameter for a list of columns to preserve types so that it doesn't convert it. That was a very useful fallback for when numbers 

Do you know if there's a way to fit contents based on cell (instead of header) on creation? Otherwise we need to manually move each column around to get something you can read.  


![Screenshot 2024-04-05 at 1 34 18 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/06fd64f9-06b2-4ba5-88d0-2c2503a44433)

![Screenshot 2024-04-05 at 1 09 02 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/c7556038-3a56-4cbb-bc73-322613695bbe)

2024-04-05 21:49 UTC, deeleeramone commented
I get an empty window when I use this function:

```
obb.equity.fundamental.ratios("AAPL")
```

The devtools shows: Invalid character '\u20ac'

2024-04-08 13:56 UTC, hjoaquim commented on openbb_platform/obbject_extensions/charting/openbb_charting/__init__.py
I don't agree - backend is treated as a global variable and will only get instantiated once. Also, I think it's a good idea to keep its initialization as centralized as possible.

2024-04-08 15:17 UTC, hjoaquim commented on openbb_platform/obbject_extensions/charting/openbb_charting/__init__.py
> +                    df_table=data_as_df,
Nice catch! Done here https://github.com/OpenBB-finance/OpenBBTerminal/pull/6290/commits/64cb679da13a7f567ba97828ad08da4bef62aab7

2024-04-08 15:18 UTC, hjoaquim commented on openbb_platform/obbject_extensions/charting/openbb_charting/__init__.py
> +                    df_table=data_as_df,
title defaults to the route - but can be changed by using the `title` argument

2024-04-08 15:54 UTC, hjoaquim commented
> I get an empty window when I use this function:
> 
> ```
> obb.equity.fundamental.ratios("AAPL")
> ```
> 
> The devtools shows: Invalid character '\u20ac'

looks like that's fixed now!

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/48914296/3fd71a8f-04b1-420d-af15-c26a141263a9)

2024-04-08 15:55 UTC, hjoaquim commented
@deeleeramone if you agree, I'll ask for a stamp here and will add the other comments to our backlog as this is needed for the CLI, and we can address those bugs later without prejudice (imo)

2024-04-08 16:37 UTC, deeleeramone commented
> if you agree, I'll ask for a stamp here and will add the other comments to our backlog as this is needed for the CLI, and we can address those bugs later without prejudice (imo)

We can definitely iterate on this going forward, but I let's nip this one in the butt first because it's such a glaring issue:
![Screenshot 2024-04-08 at 9 35 06 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/88c6bf49-c5ed-487e-af15-6429b3f3d063)

I might have an idea to patch that quickly.

2024-04-08 21:47 UTC, deeleeramone commented
@hjoaquim, could of cheap and cheerful, temporary, solutions here. This React/Tailwinds stuff is just awful to work with.

![Screenshot 2024-04-08 at 2 41 37 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/21851370-7c8b-44c5-bc5b-9f42c4be6bb0)

2024-04-08 23:21 UTC, deeleeramone approved these changes

2024-04-09 08:00 UTC, hjoaquim commented
Thanks a lot for shipping in @deeleeramone :butterfly:

2024-04-09 08:07 UTC, merged