[Feature] CLI docs
OpenBB-finance/OpenBBTerminal pull request #6362
Opened 2024-05-02 12:09 UTC by hjoaquim

# Pull Request Template for OpenBB Developers

0. **Title**:

    - Format: [Type] - Brief Description (e.g., [Hotfix] - Improve Calculation Accuracy).

1. **Why**? (1-3 sentences or a bullet point list):

    - State the primary reason for this change.

    - Example: "To enhance the accuracy of our risk calculation in response to recent market volatility."

2. **What**? (1-3 sentences or a bullet point list):

    - Describe what has been done in simple terms.

    - Example: "Updated the risk calculation algorithm to factor in real-time market fluctuations."

3. **Impact** (1-2 sentences or a bullet point list):

    - Briefly note the expected outcome or any potential risks and share the Impact Analysis score.

    - Example: "Expected to improve risk assessment accuracy by 15%, with minimal performance impact. Impact score: 10"

    > [!TIP]
    > Refer to the Impact Analysis confluence (internal) document for more information.

4. **Testing Done**:

    - A quick note on how it was tested.

    - Example: "Validated with historical market data and simulated scenarios."

5. **Reviewer Notes** (optional):

    - Any specific focus areas for review?

    - Example: "Please check algorithm compatibility with existing data models."

6. **Any other information** (optional)

TODO: 
- [ ] change color
- [ ] new image for introduction page
- [x] usage - hub
- [ ] usage - keyboard-hotkeys
- [ ] usage - data
- [ ] usage - outputs
- [ ] usage - overview
- [ ] usage routines

2024-05-02 20:27 UTC, deeleeramone commented on website/content/cli/index.md
> +![Platform Docs pic](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/74520441-5e95-4ba6-9d16-6a2d5c966cf9)
This image should go.

2024-05-02 20:31 UTC, deeleeramone commented on website/content/cli/index.md
> +sidebar_position: 0
I think the sidebar position here gets removed, and then when you click on the category label you get this page. Right now I have to expand and then click on Introduction to get the landing page.

2024-05-02 20:34 UTC, deeleeramone commented on website/content/cli/index.md
> +The OpenBB Platform CLI is a wrapper around the OpenBB Platform, this means that one can expect it to have the same functionalities that the OpenBB Platform offers with the enhancements and limitatio
This paragraph can replace the top paragraph.

2024-05-02 20:38 UTC, deeleeramone commented on website/content/cli/usage/overview/structure-and-navigation.md
> +title: Structure and Navigation
The videos in this page are not relevant and need to be removed. Generally, something you can read and reference is better for this type of material.

2024-05-02 20:41 UTC, deeleeramone commented on website/content/cli/usage/keyboard-hotkey-macros.md
> +title: Keyboard Hotkey Macros
Same goes for this page, and for essentially all video content.

2024-05-02 20:45 UTC, deeleeramone commented on website/content/cli/installation.md
> +#### Extensions
This section is redundant, we can link to the platform extensions page.

2024-05-02 20:48 UTC, deeleeramone commented on website/content/cli/usage/data/data-sources.md
> +## Relationship With Data Vendors
We don't need this section, and we can just say something like: "data sources available rely on the OpenBB Platform Provider extensions you have installed."

2024-05-02 21:11 UTC, deeleeramone commented on website/content/cli/usage/outputs/export-data.md
> +title: Export data
There is no valid syntax on this page.

2024-05-02 21:25 UTC, deeleeramone commented on website/content/cli/usage/routines/routine-macro-recorder.md
> +/record/economy/cpi/treasury/index sp500/stop
Invalid syntax

2024-05-02 21:28 UTC, deeleeramone commented on website/content/cli/usage/routines/routines-for-power-users.md
> +### Example
Not working syntax, all of these examples need to be completely redone.

2024-05-02 21:37 UTC, deeleeramone requested changes
> Tried to keep the former Terminal structure and use as much as possible the guides wrote for the terminal

Unfortunately this is not really possible. Any example syntax that existed, screenshots, etc, will be broken, and not a reflection of reality.

2024-05-12 21:24 UTC, deeleeramone commented
@hjoaquim, have a look through now. There aren't very many visual elements because things are likely to change fast.

2024-05-14 14:05 UTC, hjoaquim commented
> @hjoaquim, have a look through now. There aren't very many visual elements because things are likely to change fast.

IMO it's more than good. Amazing, thanks a lot :rocket:

2024-05-14 15:13 UTC, IgorWounds approved these changes

2024-05-14 15:42 UTC, deeleeramone approved these changes

2024-05-14 15:46 UTC, merged