[BugFix] - `dev_install.py` updates
OpenBB-finance/OpenBBTerminal pull request #6424
Opened 2024-05-16 11:54 UTC by montezdesousa

1. **Why**?

    - `dev_install.py` uses `toml` which needs to be manually installed in each environment, it's not in the dependency tree

2. **What**?

    - Replace it with `tomlkit` which is used by `poetry`, thus it's already in the dependency tree
    - Create flag to install cli locally `-c` or `--cli`, to avoid reinstalling `openbb` dependencies moved the CLI external dependencies to its own group, so you can run `poetry install --only external`

3. **Impact**

    NA

4. **Testing Done**:

    - `python dev_install.py`
    - `python dev_install.py -e`
    - `python dev_install.py -e --cli`

2024-05-16 12:31 UTC, IgorWounds approved these changes

2024-05-16 12:41 UTC, piiq requested changes

2024-05-16 12:41 UTC, piiq commented on cli/pyproject.toml
> +[tool.poetry.group.external.dependencies]
group will not be picked up by pip

2024-05-16 13:00 UTC, montezdesousa commented on cli/pyproject.toml
> +[tool.poetry.group.external.dependencies]
Yeah, I removed that then.

2024-05-16 17:14 UTC, piiq approved these changes

2024-05-16 17:16 UTC, merged

2024-09-05 14:02 UTC, dijonkitchen commented
Not sure this works with the official isolated installer: https://python-poetry.org/docs/#installing-with-the-official-installer