[Feature] Create openbb-cli .dockerfile and update docs
OpenBB-finance/OpenBBTerminal pull request #6485
Opened 2024-06-05 18:19 UTC by montezdesousa

# Pull Request Template for OpenBB Developers

0. **Title**:

    - Format: [Type] - Brief Description (e.g., [Hotfix] - Improve Calculation Accuracy).

1. **Why**? (1-3 sentences or a bullet point list):

    - State the primary reason for this change.

    - Example: "To enhance the accuracy of our risk calculation in response to recent market volatility."

2. **What**? (1-3 sentences or a bullet point list):

    - Describe what has been done in simple terms.

    - Example: "Updated the risk calculation algorithm to factor in real-time market fluctuations."

3. **Impact** (1-2 sentences or a bullet point list):

    - Briefly note the expected outcome or any potential risks and share the Impact Analysis score.

    - Example: "Expected to improve risk assessment accuracy by 15%, with minimal performance impact. Impact score: 10"

    > [!TIP]
    > Refer to the Impact Analysis confluence (internal) document for more information.

4. **Testing Done**:

    - A quick note on how it was tested.

    - Example: "Validated with historical market data and simulated scenarios."

5. **Reviewer Notes** (optional):

    - Any specific focus areas for review?

    - Example: "Please check algorithm compatibility with existing data models."

6. **Any other information** (optional)

2024-06-05 21:56 UTC, deeleeramone commented on build/docker/cli.dockerfile
> +    CMD ["openbb"]
This is going to have the exact same issues that Terminal had with Docker, the window creation processes are not particularly compatible with Docker.

```
2024 Jun 05, 17:55 (🦋) /equity/price/ $ historical --symbol aapl

/usr/local/lib/python3.11/site-packages/openbb_cli/controllers/utils.py:387: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")
/usr/local/lib/python3.11/site-packages/openbb_cli/controllers/utils.py:417: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_outgoing = df_outgoing.applymap(str)

2024 Jun 05, 17:55 (🦋) /equity/price/ $ Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pywry/core.py", line 349, in run_backend
    await self.runner.stdin.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
Exception in thread Thread-1 (run):ious menu    [e] exit the program    [cmd -h] see usage and available options    Price (cmd/menu) Documentation                                               
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pywry/core.py", line 349, in run_backend
    await self.runner.stdin.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/pywry/core.py", line 384, in run
    asyncio.run(self.run_backend())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pywry/core.py", line 358, in run_backend
    await self.run_backend()
  File "/usr/local/lib/python3.11/site-packages/pywry/core.py", line 339, in run_backend
    await self.runner.stdin.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
```

2024-06-05 21:58 UTC, deeleeramone requested changes
CLI might not be suitable for a Docker image because it really doesn't like window creation.

2024-06-06 11:22 UTC, montezdesousa commented
> CLI might not be suitable for a Docker image because it really doesn't like window creation.

It's possible to create windows (seen it with firefox and jupyter notebooks), sounds a good issue to open.

Meanwhile we keep the package with just non-interactive tables available or we remove it?

cc: @jmaslek

2024-06-06 12:48 UTC, piiq commented
I vote for removing the cli docker

2024-06-06 15:13 UTC, deeleeramone commented
> I vote for removing the cli docker

Agreed, non-interactive tables does not do anything for the charts.

2024-06-08 02:18 UTC, deeleeramone approved these changes

2024-06-12 10:16 UTC, merged